JPS/Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JPS.Data;
using JPS.Models;
using Microsoft.AspNetCore.Authorization;

namespace JPS.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class BillsController : Controller
    {
        private readonly JPSContext _context;

        public BillsController(JPSContext context)
        {
            _context = context;
        }

        // GET: Bills
        public async Task<IActionResult> Index()
        {
            return View(await _context.Bill.ToListAsync());
        }

        // GET: Bills/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bill
                .FirstOrDefaultAsync(m => m.BillId == id);
            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }

        // GET: Bills/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Bills/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BillId,GenerationDate,DueDate,PremisesNumber,CustomerId,Address,AmountDue")] Bill bill)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bill);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(bill);
        }

        // GET: Bills/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bill.FindAsync(id);
            if (bill == null)
            {
                return NotFound();
            }
            return View(bill);
        }

     





        // POST: Bills/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BillId,GenerationDate,DueDate,PremisesNumber,CustomerId,Address,AmountDue")] Bill bill)
        {
            if (id != bill.BillId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bill);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BillExists(bill.BillId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bill);
        }

        // GET: Bills/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bill
                .FirstOrDefaultAsync(m => m.BillId == id);
            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }

        // POST: Bills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bill = await _context.Bill.FindAsync(id);
            _context.Bill.Remove(bill);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BillExists(int id)
        {
            return _context.Bill.Any(e => e.BillId == id);
        }
    }
}

JPS/Views/Shared/NotFound.cshtml
@{
    ViewBag.Title = "Not Found";
}

<br /><br />
<h3 style="font-family: Times New Roman; text-align:center" class="text-danger">@ViewBag.ErrorMessage</h3>

<div class="text-center">
    <a asp-action="index" asp-controller="home">
        <img src="~/Image/NotFound.jpg" style="height:300px; width:300px" /><br />
        Click here to navigate to the home page
    </a>
</div>

JPS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

@inject SignInManager<IdentityUser> signInManager;

<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JPS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand fw-bold" style="color:yellow;" asp-area="" asp-controller="Home" asp-action="Index">JPS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a type="submit" class="nav-link btn btn-link py-0" style="width:auto" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a type="submit" class="nav-link btn btn-link py-0" style="width:auto" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        @if (signInManager.IsSignedIn(User))
                        {

                    <li class="nav-item">
                        <a type="submit" class="nav-link btn btn-link py-0" style="width:auto" asp-controller="Home" asp-action="ShowBill"> Show Bills </a>
                    </li>
                        }




                                    @if (signInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                                    {
                    <li class="nav-item">
                        <a type="submit" class="nav-link btn btn-link py-0" style="width:auto" asp-controller="Bills" asp-action="Index">Manage Bills</a>
                    </li>

                                        <li class="nav-item dropdown">
                                            <a class="nav-link dropdown-toggle nav-link btn btn-link py-0" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                Manage Roles
                                            </a>

                                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                                <a class="dropdown-item nav-link btn btn-link py-0" asp-controller="Administration" asp-action="ListUsers">Users</a>
                                                <a class="dropdown-item nav-link btn btn-link py-0" asp-controller="Administration" asp-action="ListRoles">Roles</a>
                                            </div>
                                        </li>
}
                                                </ul>
                    </div>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse" style="font-family:'Times New Roman', Times, serif">
                    <ul class="navbar-nav ml-auto">
                        @if (signInManager.IsSignedIn(User))
                        {

                  
                                    <li class="nav-item">
                                        <form method="post" asp-action="Logout" asp-controller="Account">
                                            <button type="submit" class="nav-link btn btn-link py-0" style="width:auto">
                                                Logout @User.Identity.Name
                                            </button>
                                        </form>
                                    </li>
                                }
                                else
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                                    </li>

                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                                    </li>
                                }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - JPS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>